// Copyright 2020-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import LinkableProperty from '../../axon/js/LinkableProperty.js';
import areaModelCommon from './areaModelCommon.js';

type StringsType = {
  'screen': {
    'explore': string;
    'exploreStringProperty': LinkableProperty<string>;
    'generic': string;
    'genericStringProperty': LinkableProperty<string>;
    'variables': string;
    'variablesStringProperty': LinkableProperty<string>;
    'multiply': string;
    'multiplyStringProperty': LinkableProperty<string>;
    'partition': string;
    'partitionStringProperty': LinkableProperty<string>;
    'decimals': string;
    'decimalsStringProperty': LinkableProperty<string>;
    'game': string;
    'gameStringProperty': LinkableProperty<string>;
  };
  'dimensions': string;
  'dimensionsStringProperty': LinkableProperty<string>;
  'factors': string;
  'factorsStringProperty': LinkableProperty<string>;
  'totalAreaOfModel': string;
  'totalAreaOfModelStringProperty': LinkableProperty<string>;
  'product': string;
  'productStringProperty': LinkableProperty<string>;
  'partition': string;
  'partitionStringProperty': LinkableProperty<string>;
  'areaModelCalculation': string;
  'areaModelCalculationStringProperty': LinkableProperty<string>;
  'calculation': string;
  'calculationStringProperty': LinkableProperty<string>;
  'partialProducts': string;
  'partialProductsStringProperty': LinkableProperty<string>;
  'enter': string;
  'enterStringProperty': LinkableProperty<string>;
  'area': string;
  'areaStringProperty': LinkableProperty<string>;
  'scorePrefix': string;
  'scorePrefixStringProperty': LinkableProperty<string>;
  'levelPrompt': {
    'totalArea': string;
    'totalAreaStringProperty': LinkableProperty<string>;
    'oneProduct': {
      'text': string;
      'textStringProperty': LinkableProperty<string>;
      'totalArea': string;
      'totalAreaStringProperty': LinkableProperty<string>;
      'oneLength': string;
      'oneLengthStringProperty': LinkableProperty<string>;
    };
    'twoProducts': string;
    'twoProductsStringProperty': LinkableProperty<string>;
    'twoLengths': string;
    'twoLengthsStringProperty': LinkableProperty<string>;
    'threeLengths': string;
    'threeLengthsStringProperty': LinkableProperty<string>;
  };
  'a11y': {
    'areaEqualsPattern': string;
    'areaEqualsPatternStringProperty': LinkableProperty<string>;
    'areaGrid': string;
    'areaGridStringProperty': LinkableProperty<string>;
    'areaGridRectanglePattern': string;
    'areaGridRectanglePatternStringProperty': LinkableProperty<string>;
    'areaGridSize': string;
    'areaGridSizeStringProperty': LinkableProperty<string>;
    'base10AreaTiles': string;
    'base10AreaTilesStringProperty': LinkableProperty<string>;
    'betweenCalculationLines': string;
    'betweenCalculationLinesStringProperty': LinkableProperty<string>;
    'calculationBoxTitle': string;
    'calculationBoxTitleStringProperty': LinkableProperty<string>;
    'calculationBoxDescription': string;
    'calculationBoxDescriptionStringProperty': LinkableProperty<string>;
    'countingNumbersDescription': string;
    'countingNumbersDescriptionStringProperty': LinkableProperty<string>;
    'countingNumbersLabel': string;
    'countingNumbersLabelStringProperty': LinkableProperty<string>;
    'countingNumbersPattern': string;
    'countingNumbersPatternStringProperty': LinkableProperty<string>;
    'dragHandle': string;
    'dragHandleStringProperty': LinkableProperty<string>;
    'dragHandleDescriptionPattern': string;
    'dragHandleDescriptionPatternStringProperty': LinkableProperty<string>;
    'erase': string;
    'eraseStringProperty': LinkableProperty<string>;
    'eraseDescription': string;
    'eraseDescriptionStringProperty': LinkableProperty<string>;
    'factorsBox': string;
    'factorsBoxStringProperty': LinkableProperty<string>;
    'factorsBoxDescription': string;
    'factorsBoxDescriptionStringProperty': LinkableProperty<string>;
    'factorsTimesPattern': string;
    'factorsTimesPatternStringProperty': LinkableProperty<string>;
    'gridLinesLabel': string;
    'gridLinesLabelStringProperty': LinkableProperty<string>;
    'hidePartialProducts': string;
    'hidePartialProductsStringProperty': LinkableProperty<string>;
    'horizontalDimensionCapitalized': string;
    'horizontalDimensionCapitalizedStringProperty': LinkableProperty<string>;
    'horizontalPartition': string;
    'horizontalPartitionStringProperty': LinkableProperty<string>;
    'horizontalPartitionHandle': string;
    'horizontalPartitionHandleStringProperty': LinkableProperty<string>;
    'horizontalPartitionHandleDescription': string;
    'horizontalPartitionHandleDescriptionStringProperty': LinkableProperty<string>;
    'horizontalPicker': string;
    'horizontalPickerStringProperty': LinkableProperty<string>;
    'horizontalPickerDescription': string;
    'horizontalPickerDescriptionStringProperty': LinkableProperty<string>;
    'multiplyDescription': string;
    'multiplyDescriptionStringProperty': LinkableProperty<string>;
    'onePartialProductFactorPattern': string;
    'onePartialProductFactorPatternStringProperty': LinkableProperty<string>;
    'onePartialProductPattern': string;
    'onePartialProductPatternStringProperty': LinkableProperty<string>;
    'partitionDescription': string;
    'partitionDescriptionStringProperty': LinkableProperty<string>;
    'partitionSelectionDescription': string;
    'partitionSelectionDescriptionStringProperty': LinkableProperty<string>;
    'placeholder': string;
    'placeholderStringProperty': LinkableProperty<string>;
    'productBox': string;
    'productBoxStringProperty': LinkableProperty<string>;
    'productBoxDescription': string;
    'productBoxDescriptionStringProperty': LinkableProperty<string>;
    'productTimesPattern': string;
    'productTimesPatternStringProperty': LinkableProperty<string>;
    'quantityPattern': string;
    'quantityPatternStringProperty': LinkableProperty<string>;
    'questionMark': string;
    'questionMarkStringProperty': LinkableProperty<string>;
    'sceneSelectionPattern': string;
    'sceneSelectionPatternStringProperty': LinkableProperty<string>;
    'showPartialProductFactors': string;
    'showPartialProductFactorsStringProperty': LinkableProperty<string>;
    'showPartialProducts': string;
    'showPartialProductsStringProperty': LinkableProperty<string>;
    'sumMinus': string;
    'sumMinusStringProperty': LinkableProperty<string>;
    'sumPlus': string;
    'sumPlusStringProperty': LinkableProperty<string>;
    'threePartitionsSplitPattern': string;
    'threePartitionsSplitPatternStringProperty': LinkableProperty<string>;
    'twoPartialProductFactorsPattern': string;
    'twoPartialProductFactorsPatternStringProperty': LinkableProperty<string>;
    'twoPartialProductsPattern': string;
    'twoPartialProductsPatternStringProperty': LinkableProperty<string>;
    'twoPartitionsSplitPattern': string;
    'twoPartitionsSplitPatternStringProperty': LinkableProperty<string>;
    'verticalDimensionCapitalized': string;
    'verticalDimensionCapitalizedStringProperty': LinkableProperty<string>;
    'verticalPartition': string;
    'verticalPartitionStringProperty': LinkableProperty<string>;
    'verticalPartitionHandle': string;
    'verticalPartitionHandleStringProperty': LinkableProperty<string>;
    'verticalPartitionHandleDescription': string;
    'verticalPartitionHandleDescriptionStringProperty': LinkableProperty<string>;
    'verticalPicker': string;
    'verticalPickerStringProperty': LinkableProperty<string>;
    'verticalPickerDescription': string;
    'verticalPickerDescriptionStringProperty': LinkableProperty<string>;
  }
};

const AreaModelCommonStrings = getStringModule( 'AREA_MODEL_COMMON' ) as StringsType;

areaModelCommon.register( 'AreaModelCommonStrings', AreaModelCommonStrings );

export default AreaModelCommonStrings;
